### ISSUE TITLE
zIndex unit incorrectly converted to "px"

### ISSUE THREAD

**Issue by joewood** [js-next/react-style#90]
The `zIndex` style property seems to be converted to **px** units, rather than being left as a regular integer.  For example:
```typescript
var style = ReactStyle({
    backgroundColor: "white",
    zIndex: 1
});
```

Is converted to a CSS class as
```css
XX_9 {
    background-color: white;
    z-index: 1px;
}
```

Using a string **"1"** works around the problem.
